### ISSUE TITLE
Will our programs be automatically tested?

### ISSUE THREAD

**Issue by dnc1994** [NCTU-CSE-Introduction-to-Algorithms/assignment-1-announcement-and-discussion#1]
If so, is it correct that we need to read from standard input and print to standard output?

And, what's the upper bound of the length of input sequence? While it's OK to dynamically allocate memory for the array, it's not really necessary to do that so it would be great if a upper bound is given.

Thanks.

**Comment by PeterDaveHello** [comment]
> If so, is it correct that we need to read from standard input and print to standard output?

Yes, standard input and standard output.

> And, what's the upper bound of the length of input sequence? While it's OK to dynamically allocate memory for the array, it's not really necessary to do that so it would be great if a upper bound is given.

The upper bound is 10000 inputs.

**Comment by dnc1994** [comment]
Got it. Thanks!

**Comment by tyhsu** [comment]
@PeterDaveHello You said the upper bound is 10000 inputs, but you wrote that there will be at most 1000 inputs in README.md. So what is the actual upper bound?

**Comment by dnc1994** [comment]
@dream040102 I think it's only a typo ... Anyway just set your upper bound to 10000. It can't hurt :P

**Comment by PeterDaveHello** [comment]
It's a typo, fixed.
