### ISSUE TITLE
請問可以用 c++11 的 feature 嗎？

### ISSUE THREAD

**Issue by sunset1995** [NCTU-CSE-Introduction-to-Algorithms/assignment-1-announcement-and-discussion#3]
請問可以用 c++11 的 feature 嗎？
可以請問 judge 時的編譯參數嗎？

以上
謝謝～

**Comment by PeterDaveHello** [comment]
> 請問可以用 c++11 的 feature 嗎？

Yes you can.

> 可以請問 judge 時的編譯參數嗎？

We'll consider to provide it or not.
