### ISSUE TITLE
關於assignment-1第二題

### ISSUE THREAD

**Issue by jason281** [NCTU-CSE-Introduction-to-Algorithms/assignment-1-announcement-and-discussion#5]
第二題似乎是問答題，而非寫一個程式，那要以什麼格式繳交，因為在"README.md"中提到是要教三個檔案，"prog-1.c""prog-2.c""prog-3.c"，所以是要寫成.c檔？

**Comment by PeterDaveHello** [comment]
![temp](https://cloud.githubusercontent.com/assets/3691490/13899997/777417fa-ee36-11e5-8257-1f9588db1269.png)

https://github.com/NCTU-CSE-Introduction-to-Algorithms/assignment-1-announcement-and-discussion/blob/master/README.md#filename-format

> If you don't write in C, C++ is also acceptable, just replace the extension `.c` with `.cpp`, please don't seperate your program to multiple header and class files, only one file for each program.
